# Generated by Django 5.1.5 on 2025-03-04 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_account_class_name_alter_account_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='about',
        ),
        migrations.RemoveField(
            model_name='account',
            name='date_of_birth',
        ),
    ]
