# Generated by Django 5.1.7 on 2025-03-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='check_in_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
