# Generated by Django 5.1.6 on 2025-03-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_account_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.BooleanField(default=True),
        ),
    ]
