# Generated by Django 5.1.6 on 2025-02-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_account_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('instructor', 'Instructor')], max_length=20, null=True),
        ),
    ]
