# Generated by Django 5.1.6 on 2025-03-05 13:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_account_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
