# Generated by Django 5.1.6 on 2025-03-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_account_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
